export enum ENV {
  APP_NAME = 'APP_NAME',
  APP_ENV = 'APP_ENV',
  IS_DEV = 'IS_DEV',
  IS_STG = 'IS_STG',
  IS_PRD = 'IS_PRD',
  IS_TEST = 'IS_TEST',
  APP_PORT = 'APP_PORT',
  SECRET = 'SECRET',
  ADMIN_SECRET = 'ADMIN_SECRET',
  TOKEN_EXPIRE_IN = 'TOKEN_EXPIRE_IN',

  DATABASE_URL = 'DATABASE_URL',

  CACHE_MODE = 'CACHE_MODE',
  CACHE_TTL = 'CACHE_TTL',

  REDIS_URL = 'REDIS_URL',

  LOGGER_TYPE = 'LOGGER_TYPE',
  LOGGER_MAX_FILES = 'LOGGER_MAX_FILES',

  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESCRIPTION = 'SWAGGER_DESCRIPTION',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_FAVICON = 'SWAGGER_FAVICON',
  SWAGGER_ENDPOINT = 'SWAGGER_ENDPOINT',
}

export enum CACHE_TYPE {
  REDIS = 'redis',
  MEMORY = 'memory',
}

export enum LOGGER_TYPE {
  WINSTON = 'winston',
}

export enum APP_ENV {
  DEV = 'dev',
  STG = 'stg',
  PRD = 'prd',
  TEST = 'test',
}
